// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/instances": {
    params: {};
  };
  "/instances/:instanceId/edit": {
    params: {
      "instanceId": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/configure/:blueprintId": {
    params: {
      "blueprintId": string;
    };
  };
  "/preview": {
    params: {};
  };
  "/api/entities": {
    params: {};
  };
  "/api/notify-services": {
    params: {};
  };
  "/api/instances/save": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/instances" | "/instances/:instanceId/edit" | "/settings" | "/configure/:blueprintId" | "/preview" | "/api/entities" | "/api/notify-services" | "/api/instances/save";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/instances.tsx": {
    id: "routes/instances";
    page: "/instances";
  };
  "routes/instances.$instanceId.edit.tsx": {
    id: "routes/instances.$instanceId.edit";
    page: "/instances/:instanceId/edit";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/configure.$blueprintId.tsx": {
    id: "routes/configure.$blueprintId";
    page: "/configure/:blueprintId";
  };
  "routes/preview.tsx": {
    id: "routes/preview";
    page: "/preview";
  };
  "routes/api.entities.ts": {
    id: "routes/api.entities";
    page: "/api/entities";
  };
  "routes/api.notify-services.ts": {
    id: "routes/api.notify-services";
    page: "/api/notify-services";
  };
  "routes/api.instances.save.ts": {
    id: "routes/api.instances.save";
    page: "/api/instances/save";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/instances": typeof import("./app/routes/instances.tsx");
  "routes/instances.$instanceId.edit": typeof import("./app/routes/instances.$instanceId.edit.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/configure.$blueprintId": typeof import("./app/routes/configure.$blueprintId.tsx");
  "routes/preview": typeof import("./app/routes/preview.tsx");
  "routes/api.entities": typeof import("./app/routes/api.entities.ts");
  "routes/api.notify-services": typeof import("./app/routes/api.notify-services.ts");
  "routes/api.instances.save": typeof import("./app/routes/api.instances.save.ts");
};